# Site Settings
title: Kristaps Grinbergs - Resyme
url: 'http://kristaps.me'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Kristaps Grinbergs
tagline: Swift Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '
Co-Founder, mobile developer at <a href="https://www.qminder.com/" target="_blank">Qminder</a>. Passionate about mobile applications. Love cats.
<br/><br/>
I have bachelors, masters and unfinished PhD in Computer science. Strong in iOS, tvOS, watchOS development. Passionate about mobile applications! Right now working at the easiest waiting line management in the world - Qminder.'

#sidebar links
email: fassko@gmail.com
phone: +372 58576560
website: kristaps.me #do not add http://
linkedin: kristapsgrinbergs
github: fassko
twitter: '@fassko'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-87318818-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
